config/routes.rb
Rails.application.routes.draw do
resources :blogs
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get root :to => 'homes#top'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord
  validates :title, presence: true
  validates :body, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
 
   def create
    blog = Blog.new(blog_params)
    if blog.save
        flash[:notice] = "投稿しました"
      redirect_to blog_path(blog.id)
    else
      render :index
    end
   end
  
  def index
     @blog = Blog.new
     @blogs = Blog.all
  end

  def show
   @blog = Blog.find(params[:id])
  end

  def edit
    @blog = Blog.find(params[:id])
  end
  
  def update
    blog = Blog.find(params[:id])
    if blog.update(blog_params)
        flash[:notice] = "再投稿しました"
    redirect_to blog_path(blog.id) #Showページへアクセス
    else
    render :edit
    end
  end
  
  def destroy
      blog = Blog.find(params[:id])
      blog.destroy
      redirect_to blogs_path
  end
  
  private
  def blog_params
    params.require(:blog).permit(:title, :body)
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
    
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/blogs/edit.html.erb
<h1>編集ページ</h1>
<%= form_with model: @blog, url: blog_path(@blog.id), method: :patch do |f| %>

 <h4>Title</h4>
  <%= f.text_field :title %>
  
  <h4>Body</h4>
  <%= f.text_area :body %>
  
  <%= f.submit "再投稿する" %>

<% end %>

<%= link_to "詳細を見る", blog_path(@blog.id) %>
<%= link_to "back", blogs_path %>

app/views/blogs/index.html.erb
<h1>BLOG</h1>

<strong>New Create</strong>
<% if @blog.errors.any? %>
    <%= @blog.error.count %>件入力されていません
    
    <ul>
        <% @blog.errors.full_messages. each do |message| %>
        <li><%= message %></li>
        <% end %>
    </ul>
<% end %>


<%= form_with model: @blog do |f| %>
 <h4>Title</h4>
  <%= f.text_field :title %>
  
  <h4>Body</h4>
  <%= f.text_area :body %>
  
  <%= f.submit "投稿する" %>
<% end %>

<h2>履歴</h2>

<table>
  <thead>
  <tr>
      <th>Date</th>
    <th>Title</th>
    <th colspan="3"></th>
  </tr>
  </thead>
  
   <tbody>
     <% @blogs.each do |blog| %>
  <tr>
      <td><%= l blog.created_at, format: :short %></td>
    <td><%= blog.title %></td>
    
    <td><%= link_to "編集", edit_blog_path(blog.id) %></td>
    <td><%= link_to "内容", blog_path(blog.id) %></td>
    <td><%= link_to "削除",  blog_path(blog.id), method: :delete, "data-confirm" => "削除しますか？" %></td>
  </tr>
  <% end %>
 </tbody>
</table>

app/views/blogs/show.html.erb
<h1>詳細ページ</h1>
<h4>Title</p>
<p><%= @blog.title %></p>

<h4>Body</h4>
<p><%= @blog.body %></p>

<%= link_to "編集する", edit_blog_path(@blog.id) %>
<%= link_to "Back", blogs_path %>

app/views/homes/top.html.erb
<h1>Blog</h1>

<%= link_to "Blogを書く", blogs_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FirstApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>